USE master
GO
/****** Object:  Table [dbo].[Luat]    Script Date: 11/23/2023 11:31:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Luat](
	[maluat] [char](10) NOT NULL,
	[noidung] [varchar](50) NOT NULL
) ON [PRIMARY]



GO
/****** Object:  Table [dbo].[SuKien]    Script Date: 11/23/2023 11:31:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SuKien](
	[masukien] [varchar](10) NOT NULL,
	[motasukien] [nvarchar](50) NOT NULL,
	[loaisukien] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r1        ', N'K1^HL4^N1^ST10>KL1')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r2        ', N'K1^HL4^N1^ST14>KL1')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r3        ', N'K4^HL4^N1^ST10>KL1')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r4        ', N'K4^HL4^N1^ST14>KL1')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r5        ', N'K6^HL3^N2^ST1>KL2')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r6        ', N'K6^HL4^N2^ST1>KL2')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r7        ', N'K6^HL3^N2^ST15> KL2')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r8        ', N'K6^HL4^N2^ST15>KL2')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r9        ', N'K4^HL3^N2^ST4>KL3')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r10       ', N'K4^HL4^N2^ST4>KL3')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r11       ', N'K4^HL3^N2^ST7>KL3')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r12       ', N'K4^HL4^N2^ST7>KL3')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r13       ', N'K6^HL3^N2^ST3>KL4')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r14       ', N'K6^HL4^N2^ST3>KL4')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r15       ', N'K4^HL3^N3^ST7>KL5')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r16       ', N'K4^HL4^N3^ST7>KL5')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r17       ', N'K4^HL3^N3^ST4>KL6')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r18       ', N'K4^HL4^N3^ST4>KL6')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r19       ', N'K4^HL3^N3^ST7>KL6')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r20       ', N'K4^HL4^N3^ST7>KL6')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r21       ', N'K4^HL3^N3^ST1>KL7')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r22       ', N'K4^HL4^N3^ST1>KL7')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r23       ', N'K4^HL3^N3^ST14>KL7')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r24       ', N'K4^HL4^N3^ST14>KL7')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r25       ', N'K1^HL3^N4^ST6>KL8')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r26       ', N'K1^HL4^N4^ST6>KL8')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r27       ', N'K2^HL3^N4^ST6>KL8')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r28       ', N'K2^HL4^N4^ST6>KL8')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r29       ', N'K1^HL3^N4^ST9>KL9')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r30       ', N'K1^HL4^N4^ST9>KL9')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r31       ', N'K2^HL3^N4^ST9>KL9')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r32       ', N'K2^HL4^N4^ST9>KL9')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r33       ', N'K1^HL3^N4^ST6>KL10')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r34       ', N'K1^HL4^N4^ST6>KL10')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r35       ', N'K2^HL3^N4^ST6>KL10')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r36       ', N'K2^HL4^N4^ST6>KL10')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r37       ', N'K1^HL3^N4^ST11>KL11')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r38       ', N'K1^HL4^N4^ST11>KL11')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r39       ', N'K2^HL3^N4^ST11>KL11')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r40       ', N'K2^HL4^N4^ST11>KL11')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r41       ', N'K1^HL3^N4^ST12>KL11')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r42       ', N'K1^HL4^N4^ST12>KL11')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r43       ', N'K2^HL3^N4^ST12>KL11')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r44       ', N'K2^HL4^N4^ST12>KL11')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r45       ', N'K2^HL4^N5^ST1>KL12')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r46       ', N'K1^HL4^N5^ST1>KL12')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r47       ', N'K1^HL4^N5^ST11>KL13')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r48       ', N'K2^HL4^N5^ST11>KL13')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r49       ', N'K1^HL4^N5^ST11>KL14')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r50       ', N'K3^HL4^N5^ST11>KL14')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r51       ', N'K1^HL3^N6^ST1>KL15')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r52       ', N'K1^HL3^N6^ST12>KL15')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r53       ', N'K1^HL4^N6^ST1>KL15')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r54       ', N'K1^HL4^N6^ST12>KL15')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r55       ', N'K1^HL3^N7^ST2>KL16')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r56       ', N'K1^HL4^N7^ST2>KL16')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r57       ', N'K1^HL3^N7^ST2>KL17')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r58       ', N'K1^HL4^N7^ST2>KL17')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r59       ', N'K1^HL3^N7^ST13>KL17')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r60       ', N'K1^HL4^N7^ST13>KL17')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r61       ', N'K1^HL3^N7^ST2>KL18')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r62       ', N'K1^HL4^N7^ST2>KL18')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r63       ', N'K1^HL3^N8^ST1>KL19')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r64       ', N'K1^HL4^N8^ST1>KL19')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r65       ', N'K1^HL3^N8^ST15>KL19')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r66       ', N'K1^HL4^N8^ST15>KL19')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r67       ', N'K1^HL3^N8^ST15>KL20')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r68       ', N'K1^HL4^N8^ST15>KL20')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r69       ', N'K1^HL3^N9^ST2>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r70       ', N'K1^HL3^N9^ST5>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r71       ', N'K1^HL3^N9^ST6>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r72       ', N'K1^HL4^N9^ST2>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r73       ', N'K1^HL4^N9^ST5>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r74       ', N'K1^HL4^N9^ST6>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r75       ', N'K1^HL3^N9^ST5>KL22')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r76       ', N'K1^HL4^N9^ST5>KL22')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r77       ', N'K1^HL3^N9^ST5>KL23')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r78       ', N'K1^HL4^N9^ST5>KL23')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r79       ', N'K1^HL3^N9^ST6>KL23')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r80       ', N'K1^HL4^N9^ST6>KL23')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r81       ', N'K3^HL4^N10^ST10>KL24')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r82       ', N'K3^HL4^N10^ST10>KL25')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r83       ', N'K3^HL4^N10^ST10>KL25')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r84       ', N'K6^HL2^N10^ST8>KL27')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r85       ', N'K6^HL3^N10^ST8>KL27')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r86       ', N'K6^HL4^N10^ST8>KL27')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r87       ', N'K4^HL2^N3^ST7>KL5')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r88       ', N'K6^HL2^N2^ST15>KL2')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r89       ', N'K6^HL2^N2^ST1>KL2')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r90       ', N'K1^HL2^N9^ST2>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r91       ', N'K1^HL2^N9^ST16>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r92       ', N'K1^HL2^N9^ST5>KL22')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r93       ', N'K2^HL4^N1^ST10>KL1')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r94       ', N'K2^HL4^N1^ST14>KL1')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r95       ', N'K3^HL4^N10^ST5>KL24')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r96       ', N'K3^HL4^N10^ST5>KL25')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r97       ', N'K2^HL4^N7^ST2>KL17')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r98       ', N'K2^HL3^N7^ST13>KL17')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r99       ', N'K3^HL3^N9^ST2>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r100      ', N'K3^HL3^N9^ST16>KL21')
GO
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r101      ', N'K3^HL3^N9^ST6>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r102      ', N'K3^HL4^N9^ST2>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r103      ', N'K3^HL4^N9^ST16>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r104      ', N'K3^HL4^N9^ST6>KL21')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r105      ', N'K3^HL3^N9^ST5>KL22')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r106      ', N'K3^HL4^N9^ST5>KL22')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r107      ', N'K3^HL3^N9^ST5>KL23')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r108      ', N'K3^HL4^N9^ST5>KL23')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r109      ', N'K3^HL4^N9^ST5>KL23')
INSERT [dbo].[Luat] ([maluat], [noidung]) VALUES (N'r110      ', N'K3^HL4^N9^ST6>KL23')
GO
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'K1', N'Khối A', N'Khối')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'K2', N'Khối A1', N'Khối')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'K3', N'Khối B', N'Khối')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'K4', N'Khối C', N'Khối')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'K5', N'Khối D', N'Khôi')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'K6', N'Các khối năng khiếu', N'Khối')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'HL4', N'Giỏi', N'Học Lực')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'HL1', N'Yếu', N'Học Lực')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'HL2', N'Trung Bình', N'Học Lực')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'HL3', N'Khá', N'Học Lực')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N1', N'Pháp luật', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N2', N'Nghệ thuật', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N3', N'Báo chí và thông tin', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N4', N'Kinh doanh và quản lý', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N5', N'Khoa học tự nhiên', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N6', N'Máy tính và công nghệ thông tin', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N7', N'Công nghệ kỹ thuật', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N8', N'Kiến trúc và xây dựng', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N9', N'Nông lâm nghiệp và thuỷ sản', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'N10', N'Sức khoẻ', N'Ngành')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL1', N'Luật sư', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL2', N'Mỹ thuật', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL3', N'Diễn viên', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL4', N'Thanh nhạc', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL5', N'Nhiếp ảnh', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL6', N'Báo chí', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL7', N'Công nghệ truyền thông', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL8', N'Quản trị kinh doanh', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL9', N'Marketing', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL10', N'Ngân hàng', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL11', N'Kế toán', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL12', N'Thiên văn học', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL13', N'Vật lý học', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL14', N'Hóa học', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL15', N'Công nghệ thông tin', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL16', N'Công nghệ kĩ thuật cơ khí', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL17', N'Công nghệ kĩ thuật ô tô', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL18', N'Công nghệ kĩ thuật điện điện tử', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL19', N'Kiến trúc', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL20', N'Xây dựng', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL21', N'Nông nghiệp', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL22', N'Lâm nghiệp', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL23', N'Thủy sản', N'Kết luận')
INSERT [dbo].[SuKien] ([masukien], [motasukien], [loaisukien]) VALUES (N'KL24', N'Y học', N'Kết luận')
GO
